<?php

namespace OjiePermana\Laravel\Services;

use Illuminate\Support\Facades\Http;

class BNIAPIServices
{
    /**
     * @param string $clientId  Client ID provided by BNI
     * @param string $secretKey Secret key (32 hex chars) provided by BNI
     * @param string $prefix    VA prefix number provided by BNI
     * @param string $url       BNI eCollection API URL from env BNI_ECOLLECTION_URL
     */
    public function __construct(
        private readonly string $clientId,
        private readonly string $secretKey,
        private readonly string $prefix,
        private readonly string $url = '',
    ) {}

    /**
     * Create an invoice/billing.
     *
     * @param  string      $trxId           Invoice/billing ID (max 30 chars, must be unique)
     * @param  string      $trxAmount       Amount in integer string (set to "0" for open payment billing_type "o")
     * @param  string      $billingType     Billing type: o=open, c=fixed, i=installment, m=minimum, n=open-minimum, x=open-maximum
     * @param  string      $customerName    Customer name (max 255 chars; max 14 chars for createbillingsms)
     * @param  string|null $customerEmail   Customer email (optional)
     * @param  string|null $customerPhone   Customer phone (optional; must start with 628 for createbillingsms)
     * @param  string|null $virtualAccount  16-digit VA number (optional, generated by BNI if omitted)
     * @param  string|null $datetimeExpired Expiry datetime in ISO 8601 format e.g. "2025-12-31T23:59:00+07:00" (optional)
     * @param  string|null $description     Additional info about the billing (max 100 chars, optional)
     * @param  bool        $sendSms         Send SMS notification to customer via BNI SMS Banking (default: false)
     * @return array{status: string, data: array|null}|array{status: string, message: string}
     */
    public function createBilling(
        string $trxId,
        string $trxAmount,
        string $billingType,
        string $customerName,
        ?string $customerEmail = null,
        ?string $customerPhone = null,
        ?string $virtualAccount = null,
        ?string $datetimeExpired = null,
        ?string $description = null,
        bool $sendSms = false,
    ): array {
        $data = array_filter([
            'type'             => $sendSms ? 'createbillingsms' : 'createbilling',
            'client_id'        => $this->clientId,
            'trx_id'           => $trxId,
            'trx_amount'       => $trxAmount,
            'billing_type'     => $billingType,
            'customer_name'    => $customerName,
            'customer_email'   => $customerEmail,
            'customer_phone'   => $customerPhone,
            'virtual_account'  => $virtualAccount,
            'datetime_expired' => $datetimeExpired,
            'description'      => $description,
        ], fn ($v) => $v !== null);

        return $this->request($data);
    }

    /**
     * Update an existing invoice/billing.
     *
     * Note: billing_type and virtual_account cannot be updated.
     * Note: update is only allowed when the billing has never been paid or
     *       the new amount is >= the previously paid amount.
     * Note: omitted optional fields will be replaced with empty string on BNI side.
     *
     * @param  string      $trxId           Invoice/billing ID to update
     * @param  string      $trxAmount       New amount in integer string
     * @param  string      $customerName    Customer name
     * @param  string|null $customerEmail   Customer email (optional)
     * @param  string|null $customerPhone   Customer phone (optional)
     * @param  string|null $datetimeExpired New expiry datetime in ISO 8601 format (optional)
     * @param  string|null $description     Additional info (max 100 chars, optional)
     * @return array{status: string, data: array|null}|array{status: string, message: string}
     */
    public function updateBilling(
        string $trxId,
        string $trxAmount,
        string $customerName,
        ?string $customerEmail = null,
        ?string $customerPhone = null,
        ?string $datetimeExpired = null,
        ?string $description = null,
    ): array {
        $data = array_filter([
            'type'             => 'updatebilling',
            'client_id'        => $this->clientId,
            'trx_id'           => $trxId,
            'trx_amount'       => $trxAmount,
            'customer_name'    => $customerName,
            'customer_email'   => $customerEmail,
            'customer_phone'   => $customerPhone,
            'datetime_expired' => $datetimeExpired,
            'description'      => $description,
        ], fn ($v) => $v !== null);

        return $this->request($data);
    }

    /**
     * Retrieve details of an existing invoice/billing.
     *
     * @param  string $trxId Invoice/billing ID
     * @return array{status: string, data: array|null}|array{status: string, message: string}
     */
    public function inquiryBilling(string $trxId): array
    {
        $data = [
            'type'      => 'inquirybilling',
            'client_id' => $this->clientId,
            'trx_id'    => $trxId,
        ];

        return $this->request($data);
    }

    /**
     * Send an encrypted request to BNI eCollection API.
     */
    private function request(array $data): array
    {
        $encrypted = BNIEncryptServices::Enc($data, $this->clientId, $this->secretKey);

        $payload = [
            'client_id' => $this->clientId,
            'prefix'    => $this->prefix,
            'data'      => $encrypted,
        ];

        $response = Http::withHeaders(['Content-Type' => 'application/json'])
            ->post($this->url, $payload)
            ->json();

        if (($response['status'] ?? null) === '000' && isset($response['data'])) {
            return [
                'status' => '000',
                'data'   => BNIEncryptServices::Dec($response['data'], $this->clientId, $this->secretKey),
            ];
        }

        return $response;
    }
}
